// Copyright © .NET Foundation and Contributors. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

namespace PInvoke
{
    /// <content>
    /// The <see cref="FacilityCode"/> nested type.
    /// </content>
    public partial struct HResult
    {
        /// <summary>
        /// HRESULT facility codes defined by winerror.h.
        /// </summary>
        public enum FacilityCode : uint
        {
            FACILITY_XPS = 82,
            FACILITY_XAML = 43,
            FACILITY_USN = 129,
            FACILITY_BLBUI = 128,
            FACILITY_SPP = 256,
            FACILITY_WSB_ONLINE = 133,
            FACILITY_DLS = 153,
            FACILITY_BLB_CLI = 121,
            FACILITY_BLB = 120,
            FACILITY_WSBAPP = 122,
            FACILITY_WPN = 62,
            FACILITY_WMAAECMA = 1996,
            FACILITY_WINRM = 51,
            FACILITY_WINPE = 61,
            FACILITY_WINDOWSUPDATE = 36,
            FACILITY_WINDOWS_STORE = 63,
            FACILITY_WINDOWS_SETUP = 48,
            FACILITY_WINDOWS_DEFENDER = 80,
            FACILITY_WINDOWS_CE = 24,
            FACILITY_WINDOWS = 8,
            FACILITY_WINCODEC_DWRITE_DWM = 2200,
            FACILITY_WIA = 33,
            FACILITY_WER = 27,
            FACILITY_WEP = 2049,
            FACILITY_WEB_SOCKET = 886,
            FACILITY_WEB = 885,
            FACILITY_USERMODE_VOLSNAP = 130,
            FACILITY_USERMODE_VOLMGR = 56,
            FACILITY_VISUALCPP = 109,
            FACILITY_USERMODE_VIRTUALIZATION = 55,
            FACILITY_USERMODE_VHD = 58,
            FACILITY_URT = 19,
            FACILITY_UMI = 22,
            FACILITY_UI = 42,
            FACILITY_TPM_SOFTWARE = 41,
            FACILITY_TPM_SERVICES = 40,
            FACILITY_TIERING = 131,
            FACILITY_SYNCENGINE = 2050,
            FACILITY_SXS = 23,
            FACILITY_STORAGE = 3,
            FACILITY_STATE_MANAGEMENT = 34,
            FACILITY_SSPI = 9,
            FACILITY_USERMODE_SPACES = 231,
            FACILITY_SOS = 160,
            FACILITY_SCARD = 16,
            FACILITY_SHELL = 39,
            FACILITY_SETUPAPI = 15,
            FACILITY_SECURITY = 9,
            FACILITY_SDIAG = 60,
            FACILITY_USERMODE_SDBUS = 2305,
            FACILITY_RPC = 1,
            FACILITY_RESTORE = 256,
            FACILITY_SCRIPT = 112,
            FACILITY_PARSE = 113,
            FACILITY_RAS = 83,
            FACILITY_POWERSHELL = 84,
            FACILITY_PLA = 48,
            FACILITY_PIDGENX = 2561,
            FACILITY_P2P_INT = 98,
            FACILITY_P2P = 99,
            FACILITY_OPC = 81,
            FACILITY_ONLINE_ID = 134,
            FACILITY_WIN32 = 7,
            FACILITY_CONTROL = 10,
            FACILITY_WEBSERVICES = 61,
            FACILITY_NULL = 0,
            FACILITY_NDIS = 52,
            FACILITY_NAP = 39,
            FACILITY_MOBILE = 1793,
            FACILITY_METADIRECTORY = 35,
            FACILITY_MSMQ = 14,
            FACILITY_MEDIASERVER = 13,
            FACILITY_MBN = 84,
            FACILITY_LINGUISTIC_SERVICES = 305,
            FACILITY_LEAP = 2184,
            FACILITY_JSCRIPT = 2306,
            FACILITY_INTERNET = 12,
            FACILITY_ITF = 4,
            FACILITY_INPUT = 64,
            FACILITY_USERMODE_HYPERVISOR = 53,
            FACILITY_ACCELERATOR = 1536,
            FACILITY_HTTP = 25,
            FACILITY_GRAPHICS = 38,
            FACILITY_FWP = 50,
            FACILITY_FVE = 49,
            FACILITY_USERMODE_FILTER_MANAGER = 31,
            FACILITY_EAS = 85,
            FACILITY_EAP = 66,
            FACILITY_DXGI_DDI = 2171,
            FACILITY_DXGI = 2170,
            FACILITY_DPLAY = 21,
            FACILITY_DMSERVER = 256,
            FACILITY_DISPATCH = 2,
            FACILITY_DIRECTORYSERVICE = 37,
            FACILITY_DIRECTMUSIC = 2168,
            FACILITY_DIRECT3D11 = 2172,
            FACILITY_DIRECT3D10 = 2169,
            FACILITY_DIRECT2D = 2201,
            FACILITY_DAF = 100,
            FACILITY_DEPLOYMENT_SERVICES_UTIL = 260,
            FACILITY_DEPLOYMENT_SERVICES_TRANSPORT_MANAGEMENT = 272,
            FACILITY_DEPLOYMENT_SERVICES_TFTP = 264,
            FACILITY_DEPLOYMENT_SERVICES_PXE = 263,
            FACILITY_DEPLOYMENT_SERVICES_MULTICAST_SERVER = 289,
            FACILITY_DEPLOYMENT_SERVICES_MULTICAST_CLIENT = 290,
            FACILITY_DEPLOYMENT_SERVICES_MANAGEMENT = 259,
            FACILITY_DEPLOYMENT_SERVICES_IMAGING = 258,
            FACILITY_DEPLOYMENT_SERVICES_DRIVER_PROVISIONING = 278,
            FACILITY_DEPLOYMENT_SERVICES_SERVER = 257,
            FACILITY_DEPLOYMENT_SERVICES_CONTENT_PROVIDER = 293,
            FACILITY_DEPLOYMENT_SERVICES_BINLSVC = 261,
            FACILITY_DEFRAG = 2304,
            FACILITY_DEBUGGERS = 176,
            FACILITY_CONFIGURATION = 33,
            FACILITY_COMPLUS = 17,
            FACILITY_USERMODE_COMMONLOG = 26,
            FACILITY_CMI = 54,
            FACILITY_CERT = 11,
            FACILITY_BLUETOOTH_ATT = 101,
            FACILITY_BCD = 57,
            FACILITY_BACKGROUNDCOPY = 32,
            FACILITY_AUDIOSTREAMING = 1094,
            FACILITY_AUDCLNT = 2185,
            FACILITY_AUDIO = 102,
            FACILITY_ACTION_QUEUE = 44,
            FACILITY_ACS = 20,
            FACILITY_AAF = 18,
            FACILITY_NT_BIT = 0x10000000,
        }
    }
}
