// Copyright (c) to owners found in https://github.com/AArnott/pinvoke/blob/master/COPYRIGHT.md. All rights reserved.
// Licensed under the MIT license. See LICENSE.txt file in the project root for full license information.

namespace PInvoke
{
    /// <content>
    /// The <see cref="FacilityCode"/> nested type.
    /// </content>
    public partial struct HResult
    {
        /// <summary>
        /// HRESULT facility codes defined by winerror.h
        /// </summary>
        public enum FacilityCode : uint
        {
            FACILITY_XPS = 82 << FacilityShift,
            FACILITY_XAML = 43 << FacilityShift,
            FACILITY_USN = 129 << FacilityShift,
            FACILITY_BLBUI = 128 << FacilityShift,
            FACILITY_SPP = 256 << FacilityShift,
            FACILITY_WSB_ONLINE = 133 << FacilityShift,
            FACILITY_DLS = 153 << FacilityShift,
            FACILITY_BLB_CLI = 121 << FacilityShift,
            FACILITY_BLB = 120 << FacilityShift,
            FACILITY_WSBAPP = 122 << FacilityShift,
            FACILITY_WPN = 62 << FacilityShift,
            FACILITY_WMAAECMA = 1996 << FacilityShift,
            FACILITY_WINRM = 51 << FacilityShift,
            FACILITY_WINPE = 61 << FacilityShift,
            FACILITY_WINDOWSUPDATE = 36 << FacilityShift,
            FACILITY_WINDOWS_STORE = 63 << FacilityShift,
            FACILITY_WINDOWS_SETUP = 48 << FacilityShift,
            FACILITY_WINDOWS_DEFENDER = 80 << FacilityShift,
            FACILITY_WINDOWS_CE = 24 << FacilityShift,
            FACILITY_WINDOWS = 8 << FacilityShift,
            FACILITY_WINCODEC_DWRITE_DWM = 2200 << FacilityShift,
            FACILITY_WIA = 33 << FacilityShift,
            FACILITY_WER = 27 << FacilityShift,
            FACILITY_WEP = 2049 << FacilityShift,
            FACILITY_WEB_SOCKET = 886 << FacilityShift,
            FACILITY_WEB = 885 << FacilityShift,
            FACILITY_USERMODE_VOLSNAP = 130 << FacilityShift,
            FACILITY_USERMODE_VOLMGR = 56 << FacilityShift,
            FACILITY_VISUALCPP = 109 << FacilityShift,
            FACILITY_USERMODE_VIRTUALIZATION = 55 << FacilityShift,
            FACILITY_USERMODE_VHD = 58 << FacilityShift,
            FACILITY_URT = 19 << FacilityShift,
            FACILITY_UMI = 22 << FacilityShift,
            FACILITY_UI = 42 << FacilityShift,
            FACILITY_TPM_SOFTWARE = 41 << FacilityShift,
            FACILITY_TPM_SERVICES = 40 << FacilityShift,
            FACILITY_TIERING = 131 << FacilityShift,
            FACILITY_SYNCENGINE = 2050 << FacilityShift,
            FACILITY_SXS = 23 << FacilityShift,
            FACILITY_STORAGE = 3 << FacilityShift,
            FACILITY_STATE_MANAGEMENT = 34 << FacilityShift,
            FACILITY_SSPI = 9 << FacilityShift,
            FACILITY_USERMODE_SPACES = 231 << FacilityShift,
            FACILITY_SOS = 160 << FacilityShift,
            FACILITY_SCARD = 16 << FacilityShift,
            FACILITY_SHELL = 39 << FacilityShift,
            FACILITY_SETUPAPI = 15 << FacilityShift,
            FACILITY_SECURITY = 9 << FacilityShift,
            FACILITY_SDIAG = 60 << FacilityShift,
            FACILITY_USERMODE_SDBUS = 2305 << FacilityShift,
            FACILITY_RPC = 1 << FacilityShift,
            FACILITY_RESTORE = 256 << FacilityShift,
            FACILITY_SCRIPT = 112 << FacilityShift,
            FACILITY_PARSE = 113 << FacilityShift,
            FACILITY_RAS = 83 << FacilityShift,
            FACILITY_POWERSHELL = 84 << FacilityShift,
            FACILITY_PLA = 48 << FacilityShift,
            FACILITY_PIDGENX = 2561 << FacilityShift,
            FACILITY_P2P_INT = 98 << FacilityShift,
            FACILITY_P2P = 99 << FacilityShift,
            FACILITY_OPC = 81 << FacilityShift,
            FACILITY_ONLINE_ID = 134 << FacilityShift,
            FACILITY_WIN32 = 7 << FacilityShift,
            FACILITY_CONTROL = 10 << FacilityShift,
            FACILITY_WEBSERVICES = 61 << FacilityShift,
            FACILITY_NULL = 0 << FacilityShift,
            FACILITY_NDIS = 52 << FacilityShift,
            FACILITY_NAP = 39 << FacilityShift,
            FACILITY_MOBILE = 1793 << FacilityShift,
            FACILITY_METADIRECTORY = 35 << FacilityShift,
            FACILITY_MSMQ = 14 << FacilityShift,
            FACILITY_MEDIASERVER = 13 << FacilityShift,
            FACILITY_MBN = 84 << FacilityShift,
            FACILITY_LINGUISTIC_SERVICES = 305 << FacilityShift,
            FACILITY_LEAP = 2184 << FacilityShift,
            FACILITY_JSCRIPT = 2306 << FacilityShift,
            FACILITY_INTERNET = 12 << FacilityShift,
            FACILITY_ITF = 4 << FacilityShift,
            FACILITY_INPUT = 64 << FacilityShift,
            FACILITY_USERMODE_HYPERVISOR = 53 << FacilityShift,
            FACILITY_ACCELERATOR = 1536 << FacilityShift,
            FACILITY_HTTP = 25 << FacilityShift,
            FACILITY_GRAPHICS = 38 << FacilityShift,
            FACILITY_FWP = 50 << FacilityShift,
            FACILITY_FVE = 49 << FacilityShift,
            FACILITY_USERMODE_FILTER_MANAGER = 31 << FacilityShift,
            FACILITY_EAS = 85 << FacilityShift,
            FACILITY_EAP = 66 << FacilityShift,
            FACILITY_DXGI_DDI = 2171 << FacilityShift,
            FACILITY_DXGI = 2170 << FacilityShift,
            FACILITY_DPLAY = 21 << FacilityShift,
            FACILITY_DMSERVER = 256 << FacilityShift,
            FACILITY_DISPATCH = 2 << FacilityShift,
            FACILITY_DIRECTORYSERVICE = 37 << FacilityShift,
            FACILITY_DIRECTMUSIC = 2168 << FacilityShift,
            FACILITY_DIRECT3D11 = 2172 << FacilityShift,
            FACILITY_DIRECT3D10 = 2169 << FacilityShift,
            FACILITY_DIRECT2D = 2201 << FacilityShift,
            FACILITY_DAF = 100 << FacilityShift,
            FACILITY_DEPLOYMENT_SERVICES_UTIL = 260 << FacilityShift,
            FACILITY_DEPLOYMENT_SERVICES_TRANSPORT_MANAGEMENT = 272 << FacilityShift,
            FACILITY_DEPLOYMENT_SERVICES_TFTP = 264 << FacilityShift,
            FACILITY_DEPLOYMENT_SERVICES_PXE = 263 << FacilityShift,
            FACILITY_DEPLOYMENT_SERVICES_MULTICAST_SERVER = 289 << FacilityShift,
            FACILITY_DEPLOYMENT_SERVICES_MULTICAST_CLIENT = 290 << FacilityShift,
            FACILITY_DEPLOYMENT_SERVICES_MANAGEMENT = 259 << FacilityShift,
            FACILITY_DEPLOYMENT_SERVICES_IMAGING = 258 << FacilityShift,
            FACILITY_DEPLOYMENT_SERVICES_DRIVER_PROVISIONING = 278 << FacilityShift,
            FACILITY_DEPLOYMENT_SERVICES_SERVER = 257 << FacilityShift,
            FACILITY_DEPLOYMENT_SERVICES_CONTENT_PROVIDER = 293 << FacilityShift,
            FACILITY_DEPLOYMENT_SERVICES_BINLSVC = 261 << FacilityShift,
            FACILITY_DEFRAG = 2304 << FacilityShift,
            FACILITY_DEBUGGERS = 176 << FacilityShift,
            FACILITY_CONFIGURATION = 33 << FacilityShift,
            FACILITY_COMPLUS = 17 << FacilityShift,
            FACILITY_USERMODE_COMMONLOG = 26 << FacilityShift,
            FACILITY_CMI = 54 << FacilityShift,
            FACILITY_CERT = 11 << FacilityShift,
            FACILITY_BLUETOOTH_ATT = 101 << FacilityShift,
            FACILITY_BCD = 57 << FacilityShift,
            FACILITY_BACKGROUNDCOPY = 32 << FacilityShift,
            FACILITY_AUDIOSTREAMING = 1094 << FacilityShift,
            FACILITY_AUDCLNT = 2185 << FacilityShift,
            FACILITY_AUDIO = 102 << FacilityShift,
            FACILITY_ACTION_QUEUE = 44 << FacilityShift,
            FACILITY_ACS = 20 << FacilityShift,
            FACILITY_AAF = 18 << FacilityShift,
            FACILITY_NT_BIT = 4096 << FacilityShift,
        }
    }
}
