// Copyright (c) to owners found in https://github.com/AArnott/pinvoke/blob/master/COPYRIGHT.md. All rights reserved.
// Licensed under the MIT license. See LICENSE.txt file in the project root for full license information.

namespace PInvoke
{
    using System;
    using System.Runtime.InteropServices;

    /// <content>
    /// Contains the <see cref="HARDWAREINPUT"/> nested type.
    /// </content>
    public partial class User32
    {
        /// <summary>
        /// Contains information about a simulated message generated by an input device other than a keyboard or mouse.
        /// </summary>
        [StructLayout(LayoutKind.Sequential)]
        public struct HARDWAREINPUT
        {
            /// <summary>
            /// The message generated by the input hardware.
            /// </summary>
            public uint uMsg;

            /// <summary>
            /// The low-order word of the lParam parameter for <see cref="uMsg"/>.
            /// </summary>
            public ushort wParamL;

            /// <summary>
            /// The high-order word of the lParam parameter for <see cref="uMsg"/>.
            /// </summary>
            public ushort wParamH;
        }
    }
}